version: '3.8'
services:
  web:
    build:
      context: .
    restart: always
    ports:
      - "10075:8080"
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - bacabaca/.env
    depends_on:
      - db
    networks:
      - frontend-network
      - backend-network

  db:
    image: postgres:14-alpine
    ports:
      - '15075:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  db:
    driver: local

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge